inherit_gem:
  sgcop: rails/rubocop.yml

AllCops:
  Exclude:
    - "vendor/**/*"
    - "db/schema.rb"
    - "node_modules/**/*"
    - "db/migrate/**/*"
    - "app/channels/**/*"
    - "config/**/*"
    - "bin/**/*"
    - "tmp/**/*"
    - "log/**/*"
    - "Rakefile"
